#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

tsn = env.Library('tsn',
                  ['tsn_vrf_listener.cc',
                  ])
