#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

import sys
if sys.platform == 'darwin':
    Return()

import re
import time
import subprocess

Import('AgentEnv')
env = AgentEnv.Clone()

# Function to append TOP level directory
def AddTopDir(list):
    return map(lambda x: Dir(env['TOP'] + '/' + x).abspath, list)

env.Append(CPPPATH = AddTopDir(['ovsdb-client/']))
env.Append(LIBPATH = [
        '../tables',
        '../ovsdb_client'
        ])
env.Prepend(LIBS = [
        'vnswinit',
        'ovsdbclient',
        'openvswitch'
        ])
env.Append(LIBS = [ 'physical_devices' ])

env.GenerateBuildInfoCode(
    target='buildinfo.cc',
    source = ['main.cc'],
    path=str(Dir('.').abspath))

env = AgentEnv.RemoveExceptionFlag(env)
env.AppendUnique(CCFLAGS='-Wno-reorder')
env.AppendUnique(CCFLAGS='-Wno-return-type')

tor_agent = env.Program(target = 'tor_agent',
                        source = [
                                  'buildinfo.cc',
                                  'tor_agent_param.cc',
                                  'tor_agent_init.cc',
                                  'main.cc',
                                 ])

env.Alias('agent:tor_agent', tor_agent)

# Local Variables:
# mode: python
# End:
